jobs:
  validate-and-send:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Install GitHub CLI
      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      # Validate files, add timestamp, send to backend...
      - name: Check changed files
        run: |
          CHANGED=$(git diff --name-only HEAD^ HEAD)
          if [ "$CHANGED" != "Actions/Action.json" ]; then
            echo "❌ Only Actions/Action.json can be modified."
            exit 1
          fi

      - name: Validate JSON fields
        run: |
          if ! jq empty Actions/Action.json; then
            echo "❌ Invalid JSON syntax"
            exit 1
          fi
          ACTION=$(jq -r '.action' Actions/Action.json)
          NAME=$(jq -r '.name' Actions/Action.json)
          if [ -z "$ACTION" ] || [ -z "$NAME" ] || [ "$ACTION" = "null" ] || [ "$NAME" = "null" ]; then
            echo "❌ 'action' and 'name' fields must exist and not be empty"
            exit 1
          fi
          echo "ACTION=$ACTION" >> $GITHUB_ENV
          echo "NAME=$NAME" >> $GITHUB_ENV

      - name: Add timestamp
        run: |
          timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          jq --arg time "$timestamp" '.timestamp = $time' Actions/Action.json > tmp.json && mv tmp.json Actions/Action.json

      - name: Send action to backend
        run: |
          curl -X POST https://faction-turf.vercel.app/api/postInfo \
            -H "Content-Type: application/json" \
            -d "{\"username\":\"${{ env.NAME }}\", \"action\":\"${{ env.ACTION }}\", \"timestamp\":\"$(jq -r '.timestamp' Actions/Action.json)\"}"

      - name: Close PR
        run: |
          gh pr close ${{ github.event.pull_request.number }} \
            --comment "✅ Action processed and timestamp added automatically!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
