name: Validate, Timestamp, Send, and Close PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  validate-and-send:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2️⃣ Install GitHub CLI
      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      # 3️⃣ Ensure only Actions/Action.json is changed
      - name: Check changed files
        run: |
          CHANGED=$(git diff --name-only HEAD^ HEAD)
          echo "Changed files: $CHANGED"
          if [ "$CHANGED" != "Actions/Action.json" ]; then
            echo "❌ Only Actions/Action.json can be modified."
            exit 1
          fi

      # 4️⃣ Validate JSON fields
      - name: Validate JSON
        run: |
          if ! jq empty Actions/Action.json; then
            echo "❌ Invalid JSON syntax"
            exit 1
          fi
          ACTION=$(jq -r '.action' Actions/Action.json)
          NAME=$(jq -r '.name' Actions/Action.json)
          if [ -z "$ACTION" ] || [ -z "$NAME" ] || [ "$ACTION" = "null" ] || [ "$NAME" = "null" ]; then
            echo "❌ 'action' and 'name' fields must exist and not be empty"
            exit 1
          fi
          echo "✅ Found action='$ACTION', name='$NAME'"
          echo "ACTION=$ACTION" >> $GITHUB_ENV
          echo "NAME=$NAME" >> $GITHUB_ENV

      # 5️⃣ Add timestamp
      - name: Add timestamp
        run: |
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          jq --arg time "$TIMESTAMP" '.timestamp = $time' Actions/Action.json > tmp.json && mv tmp.json Actions/Action.json
          echo "✅ Updated Actions/Action.json with timestamp:"
          cat Actions/Action.json
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV

      # 6️⃣ Send JSON to backend
      - name: Send action to backend
        run: |
          curl -X POST https://faction-turf.vercel.app/api/postInfo \
            -H "Content-Type: application/json" \
            -d "{\"username\":\"${{ env.NAME }}\", \"action\":\"${{ env.ACTION }}\", \"timestamp\":\"${{ env.TIMESTAMP }}\"}"

      # 7️⃣ Close PR automatically
      - name: Close PR
        run: |
          gh pr close ${{ github.event.pull_request.number }} \
            --comment "✅ Action processed and timestamp added automatically!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
